name: Labels
on:
  push:

permissions:
  issues: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: my-script
        with:
          script: |
            console.log(await github.rest.issues.listLabelsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            }))
