name: Labels
on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  example:
    name: adds labels
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/rate_limit
      # Add labels to an issue in this repository
      - name: Add Labels
        id: add-labels
        uses: issue-ops/labeler@v2
        with:
          action: add
          create: false # lol i guess this doesnt matter/does nothing
          issue_number: 1
          labels: |
            special-label

  test:
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            console.log(await github.rest.issues.listLabelsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            }))
      
      - uses: actions/github-script@v7
        with:
          script: |
            try {
              console.log(await github.rest.issues.createLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'srtjaws45eyu45s ujs4erujs4r6jsdr6ykjrdsykdrtylkdtysrtjaws45eyu45s ujs4erujs4r6jsdr6ykjrdsykdrtylkdty'
              }))
            } catch(e) {
              console.log('error', e);
            }
