name: Test Parse YAML

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write
  
jobs:
  test-parse-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@v2.0.0

      - run: echo "$JSON"
        env:
          JSON: ${{ fromJSON(steps.parse.outputs.data).package-json.text }}
