name: Test My
on:
  push:
  
jobs:
  test-parse:
    runs-on: ubuntu-latest
    steps:
      - name: Test Local Action - Body
        id: test
        uses: benlei/issue-templateless-parser@v1
        with:
          issue-number: 0
