name: Test Parse YAML

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write
  
jobs:
  test-parse-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Get Issue by title
        id: issue
        run: |
          gh issue list --repo benlei/sandbox --search "Test Issue" --json number -L 1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@v2.2.0

      - run: echo "$JSON"
        env:
          JSON: ${{ fromJSON(steps.parse.outputs.data).package-json.text }}
