name: Test My Parser
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test-my-parser.yml'

jobs:
  test-parse:
    runs-on: ubuntu-latest
    steps:
      - name: Parse Markdown Table
        uses: benlei/parse-simple-md-table@v1
        id: parse-table
        with:
          markdown: |
            | Hello World | Goodbye World |
            | --- | --- |
            | 123 | abc |
            | foo | bar |
  
      - name: Output first row first column
        run: echo ${{ fromJSON(steps.parse-table.outputs.result)[0]['Hello World'] }}
