name: Test Parse YAML

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write
  
jobs:
  test-parse-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Get Issue by title
        id: issue
        run: |
          gh api graphql --paginate -f query='
            {
              repository(owner: "OWNER", name: "REPO") {
                issues(first: 1, filterBy: {title: "Foobar Issue"}) {
                  nodes {
                    id
                    title
                    body
                    url
                  }
                }
              }
            }' --jq '.data.repository.issues.nodes[0] | {number: .number}'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@v2.2.0

      - run: echo "$JSON"
        env:
          JSON: ${{ fromJSON(steps.parse.outputs.data).package-json.text }}
